services:
  db:
    image: mysql:8.0
    container_name: gilab_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'gilab'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    # ports:
      # To connect from local machine for debugging, etc.
      # - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 3s

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: gilab_backend
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      # Mount the server code for live-reloading during development
      - ./server:/app
      - ./server/uploads:/app/uploads
      - ./server/static:/app/static
    env_file:
      - ./server/.env
    environment:
      PYTHONPATH: /app
      PUBLIC_BASE_URL: https://locking-led-hobby-labs.trycloudflare.com

    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: node:18-alpine
    container_name: gilab_frontend
    restart: unless-stopped
    working_dir: /app/client
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: gilab_nginx
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:80"
      - "0.0.0.0:8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend

volumes:
  db_data: