services:
  db:
    image: mysql:8.0
    container_name: gilab_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'gilab'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    # ports:
      # To connect from local machine for debugging, etc.
      # - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 3s

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: gilab_backend
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      # Mount the server code for live-reloading during development
      - ./server:/app
      - ./server/uploads:/app/uploads
      - ./server/static:/app/static
    env_file:
      - ./server/.env
    environment:
      PYTHONPATH: /app
      PUBLIC_BASE_URL: http://localhost:8000

    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: gilab_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data: